Upgrade to Ubuntu 20.04
This upgrade requires more packages to be upgraded:

ffmpeg 4.2.2
chrome 83.0.4103.116
firefox 77.0.1
pip 20.1.1 -> To skip pip warning
supervisor 4.2.0 -> To fix failing "ImportError: cannot import name escape' from 'cgi'"
change from apt to apt-get -> To remove warning "unstable cli interface"

pending next stable release:
TODO: upgrade sudo to 1.8.31p1 or 1.9 to fix
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
https://github.com/sudo-project/sudo/issues/42